import os
from dotenv import load_dotenv
load_dotenv()

ELEVENLABS_VOICE_ID = os.getenv("ELEVENLABS_VOICE_ID","N69ME3CXdq0F9L9czkig")
ELEVENLABS_MODEL_ID = os.getenv("ELEVENLABS_MODEL_ID","eleven_turbo_v2_5")
ELEVENLABS_SPEED = os.getenv("ELEVENLABS_SPEED","1.1")
ELEVENLABS_STABILITY = os.getenv("ELEVENLABS_STABILITY","0.8")
ELEVENLABS_SIMILARITY = os.getenv("ELEVENLABS_SIMILARITY","0.65")
ELEVEN_LABS_DICTIONARY = os.getenv("ELEVEN_LABS_DICTIONARY","")


# Langfuse
LANGFUSE_PUBLIC_KEY = os.getenv("LANGFUSE_PUBLIC_KEY")
LANGFUSE_SECRET_KEY = os.getenv("LANGFUSE_SECRET_KEY")
LANGFUSE_HOST = os.getenv("LANGFUSE_HOST", "https://langfuse.outscal.com")

WEBSITE_URL="https://outscal.com"

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.getenv("AWS_REGION","ap-south-1")

# Payload CMS API
PAYLOAD_API_BASE_URL = os.getenv("PAYLOAD_API_BASE_URL","https://admin-v2.outscal.com")
PAYLOAD_AUTH_TOKEN = os.getenv("PAYLOAD_AUTH_TOKEN")

PROMPT_TAG = "production"
MANIFEST_FILE="Outputs/{topic}/manifest.json"

DIRECTION_PROMPT_TAG = os.getenv("DIRECTION_PROMPT_TAG", PROMPT_TAG)
ASSETS_PROMPT_TAG = os.getenv("ASSETS_PROMPT_TAG", PROMPT_TAG)
DESIGN_PROMPT_TAG = os.getenv("DESIGN_PROMPT_TAG", PROMPT_TAG)
VIDEO_PROMPT_TAG = os.getenv("VIDEO_PROMPT_TAG", PROMPT_TAG)